
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: servicio-sensor
          uri: lb://servicio-sensor
          predicates:
            - Path=/sensor/**
        - id: servicio-lectura
          uri: lb://servicio-lectura
          predicates:
            - Path=/lectura/**
        - id: servicio-invernadero
          uri: lb://servicio-invernadero
          predicates:
            - Path=/invernadero/**
        - id: servicio-cultivo
          uri: lb://servicio-cultivo
          predicates:
            - Path=/cultivo/**