spring:
  application:
    name: servicio-invernadero
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/proyecto
    username: root
    password: 1234
