version: '3'
services:
    mysql-server:
        image: mysql:8.0.17
        container_name: proyecto-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: proyecto
        ports:
            - 3308:3306
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
        ports:
          - "5672:5672"
          - "15672:15672"
      